"""unique=True

Revision ID: 623a245d02d8
Revises: caeec6ef715e
Create Date: 2024-12-29 00:47:52.957028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623a245d02d8'
down_revision: Union[str, None] = 'caeec6ef715e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_id', table_name='wallet')
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.create_index('ix_wallet_id', 'wallet', ['id'], unique=False)
    # ### end Alembic commands ###
