"""index=True

Revision ID: caeec6ef715e
Revises: 493dbc1f5df9
Create Date: 2024-12-29 00:44:34.503857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeec6ef715e'
down_revision: Union[str, None] = '493dbc1f5df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    # ### end Alembic commands ###
